version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mount the entire project directory to /app in the container (for dev only)
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    networks:
      - app_network

  redis:
    image: redis:alpine
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
